### ISSUE TITLE
windows 10 系统 clone项目报错

### ISSUE THREAD

**Issue by LydiaAgute** [ChenyangGao/ituring_books#4]
error: invalid path '图灵程序设计丛书/[图灵图书].可能与不可能的边界：P:NP问题趣史.pdf'
怀疑是书名当中的冒号导致的问题

**Comment by ChenyangGao** [comment]
我名字已经改了，把:改成了／，你再试试

**Comment by LydiaAgute** [comment]
已经修复了，感谢分享
